### ISSUE TITLE
CVE Regex too short

### ISSUE THREAD

**Issue by StephenBrown2** [evitalis/cvechk.net#5]
https://github.com/evitalis/cvechk.net/blob/master/cvechk/utils.py#L15

doesn't match the new guidelines for longer CVE numbers: 

https://cve.mitre.org/cve/identifiers/syntaxchange.html

There is no limit on the number of arbitrary digits. They can have 4, 5, 6, 7, 8, etc...

Should probably change to `r'CVE-[0-9]{4}-[0-9]{4,}'`

**Comment by StephenBrown2** [comment]
Oh nice, the technical guidance even provides an appropriate regex for strict matching: `/^CVE-\d{4}-(0\d{3}|[1-9]\d{3,})$/` which of course should me loosened just a little to not care about beginning and end of the string:

`/CVE-\d{4}-(0\d{3}|[1-9]\d{3,})/`

https://cve.mitre.org/cve/identifiers/tech-guidance.html

**Comment by evitalis** [comment]
Fixed by  d677e02
